# Generated by Django 5.0.7 on 2024-07-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excelapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exceldata",
            name="Name",
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Category",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="City",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Country",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Customer_ID",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Customer_Name",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Discount",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Order_Date",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Order_ID",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Postal_Code",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Product_ID",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Product_Name",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Profit",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Quantity",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Region",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Row_ID",
            field=models.CharField(default="Berlin", max_length=225),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Sales",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Segment",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Ship_Date",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Ship_Mode",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="State",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AddField(
            model_name="exceldata",
            name="Sub_Category",
            field=models.CharField(default="Berlin", max_length=255),
        ),
        migrations.AlterField(
            model_name="exceldata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
