# Generated by Django 5.0.7 on 2024-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excelapp", "0003_alter_exceldata_row_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exceldata",
            name="Order_Date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="exceldata",
            name="Ship_Date",
            field=models.DateTimeField(blank=True),
        ),
    ]
